import React, {ReactElement} from "react";

export default function TermsOfUse(): ReactElement {
  return (
    <div className="terms__contentbox">
      <p><strong>KYOKAN GROUP</strong></p>
      <p><strong>TERMS OF SERVICE</strong></p>
      <p><em>Effective Date: March 14th, 2020</em></p>
      <p>These Terms of Service (the “Terms”) are a binding contract between you and Kyokan Group (“Kyokan,” “we”  and “us”) and establish the rules and restrictions that govern your use of our products, services and applications, including, but not limited to, (i) our website located at www.kyokan.io (the “Site”) and (ii) a digital wallet (the “Wallet”  ) consisting of software developed by us (our “Software”) that permits you to self-custody and transact in the Handshake virtual currency (“HNS”) participate in domain name auctions and conduct other interactions on the Handshake blockchain network (“Handshake” or the “Handshake Network”  ), and otherwise use HNS on the Handshake network (such products, services and applications including the Site and Wallet are collectively, the “Services”  ). If you have any questions, comments, or concerns regarding these Terms or the Services, please contact us at operations@kyokan.io. These Terms include the provisions in this document, as well as those in the Privacy Policy:</p>
      <p><a href="https://github.com/kyokan/agreements/blob/main/Kyokan_PP_Latest_10282020.pdf">https://github.com/kyokan/agreements/blob/main/Kyokan_PP_Latest_10282020.pdf</a>.</p>
      <p>IF YOU DO NOT AGREE TO ALL OF THE FOLLOWING TERMS, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER. THESE TERMS CONTAIN A BINDING ARBITRATION CLAUSE AND CLASS ACTION WAIVER, WHICH MAY AFFECT YOUR LEGAL RIGHTS. PLEASE READ IT CAREFULLY. YOUR USE OF THE SERVICES IN ANY WAY MEANS THAT YOU AGREE TO ALL OF THESE TERMS, AND THESE TERMS WILL REMAIN IN EFFECT WHILE YOU USE THE SERVICES.</p>
      <p><strong>Will these Terms ever change?</strong></p>
      <p>We are constantly trying to improve our Services, so we may need to change these Terms along with the Services. We reserve the right to change the Terms at any time, but if we do, we will bring it to your attention by requiring you to log in to our Services again and accept the new Terms, and/or by some other means.</p>
      <p>If you don’t agree with the new Terms, you are free to reject them. Unfortunately, that means you may not be able to use some of the Services. However, we have no access to the HNS in your Wallet, and you can always access your HNS using the seed phrase you have used to create your Wallet or that was generated with our Software when you created your Wallet in any other compatible Handshake Wallet, although we make no guarantees on the performance of other Handshake Wallets not developed by us. We also cannot prevent you from using prior versions of our Wallet to access your HNS if you disagree with new Terms, although you may be required to agree to new terms for future iterations of our Wallet or other Services.</p>
      <p>If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes. Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.</p>
      <p><strong>Who can use the Services?</strong></p>
      <p>By accessing or using our Services, you represent and warrant that you are of legal age in your jurisdiction as is required to access such Services and enter into arrangements as provided by the Services (or if not, you’ve received your parent’s or guardian’s permission to use the Services and gotten your parent or guardian to agree to these Terms on your behalf). If you’re agreeing to these Terms on behalf of an organization or entity, you represent and warrant that you are authorized to agree to these Terms on that organization or entity’s behalf and bind them to these Terms (in which case, the references to “you” and “your”  in these Terms, except for in this sentence, refer to that organization or entity.). You will only use the Services for your own internal, personal use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws or regulations, or you are a citizen, resident, or member of any jurisdiction or group that is subject to economic sanctions by the United States, then you aren’t authorized to use the Services. If permits and licenses are required for you to use the Services, you must first obtain those prior to such use. We can’t and won’t be responsible for your using the Services in a way that breaks the law or regulations.</p>
      <p><strong>What about my privacy?</strong></p>
      <p>Kyokan takes the privacy of its users seriously. To view Kyokan’s current Privacy Policy, please click here: <a href="https://github.com/kyokan/agreements/blob/main/Kyokan_PP_Latest_10282020.pdf">https://github.com/kyokan/agreements/blob/main/Kyokan_PP_Latest_10282020.pdf</a>.</p>
      <p>What are the basics of using Kyokan’s Services?</p>
      <p>Other than the Site, the Services primarily consist of the Wallet that can store and transfer HNS and allows users to interact with the Handshake Network. The Handshake Network is a decentralized blockchain network not developed by us that allows for network participants to purchase, sell, acquire and use top-level domain names (“TLDs”  ) hosted on the Handshake Network. Specifically, Handshake Network participants can purchase TLDs by participating in auctions that allow such participants to bid on TLDs as part of a Vickrey auction. The owner of a Handshake TLD can use its TLD in a variety of ways, including but not limited to offering subdomain services, hosting censorship-resistant websites, or reselling TLDs to other interested parties. In addition, certain users may be eligible to claim HNS that was allocated to them in a randomized process by the creators of the Handshake Network. Users of our Wallet can claim or transfer HNS and directly participate in interactions on the Handshake Network directly from an interface within the Wallet.</p>
      <p>Kyokan does not create, host, facilitate, participate, or otherwise enable transactions on the Handshake Network and has no control over the results of the auctions that occur on the Handshake Network, a user’s eligibility to receive HNS, transfers between Handshake Network participants, or any other activity that occurs on the Handshake Network. The Wallet is essentially an interface for users to interact directly with Handshake and to self-custody HNS.</p>
      <p>When you create a Wallet, you will either provide a seed phrase to generate that Wallet or a cryptographic private and public key pair will be generated. Such private key may be in the form of a mnemonic seed phrase. Regardless, the private and public key pair together evidence ownership/possession of a specific amount of HNS in that Wallet which enables you to send and receive HNS via the Handshake Network. The public key is visible to all participants of the Handshake Network. The private key must be used to transact the HNS represented by the corresponding public key. You will also create a password to access your Wallet and your private key as a security or convenience measure. In this instance, your password method may function similarly to your private key in that it allows you and others in possession of such information to potentially transfer HNS from your Wallet if they have access to your Wallet. Kyokan does not store your private key or any similar methods of accessing your private key, and we will never request this information.</p>
      <p>You will be responsible for keeping your hardware devices, including your personal computing device or phone, secure and for any activity associated with such devices and your Wallet. Kyokan will not be responsible if someone else accesses your devices and authorizes a transaction from your Wallet.</p>
      <p>Kyokan does not have access to your private key or password and cannot access your Wallet, initiate a transfer of HNS or otherwise access the Handshake Network using your Wallet. We are not your brokers, intermediaries, agents, advisors, or custodians, and we do not have a fiduciary relationship or obligation to you regarding any other decisions or activities that you affect when using your Wallet or our Services. We are not responsible for any activities that you engage in when using your Wallet, and you should understand the risks associated with Virtual Currency, including HNS, described more fully below. Unless explicitly provided in writing, we do not host or maintain any applications or Handshake services that may be accessible using our Services and do not participate in any Handshake transactions, recommend, endorse, or otherwise take a position on your use of these Services.</p>
      <p>“<em>Virtual Currency</em>”  refers to cryptocurrency, digital currency, digital asset, crypto asset or other such similar term describing, for example, Ethereum, but does not include a derivative of a virtual currency or a security. Virtual Currency is evidenced on, and can be electronically transferred using a Blockchain.</p>
      <p>“<em>Blockchain</em>” refers to a distributed ledger, maintained by a network of computers, that records all transactions of Virtual Currency in theoretically unchangeable data packages known as blocks, each of which are timestamped to reference the previous block, so that the blocks are linked in a chain that evidences the entire history of transactions of the Virtual Currency.</p>
      <p>Your use of the Services is subject to the following additional restrictions:</p>
      <p>You represent, warrant, and agree that you will not use the Services or interact with the Services in a manner that:</p>
      <ul>
        <li><p>Infringes or violates the intellectual property rights or any other rights of anyone else (including Kyokan);</p>
        </li>
        <li><p>Violates any law or regulation, including, without limitation, any applicable export control laws;</p>
        </li>
        <li><p>Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;</p>
        </li>
        <li><p>Jeopardizes the security of your Wallet or anyone else’s (such as allowing someone else to log in to the Services as you);</p>
        </li>
        <li><p>Attempts, in any manner, to obtain the private key, password or other security information from any other user;</p>
        </li>
        <li><p>Attempts to access another user’s Wallet, private key or other security information on any third-party site or services that provide access to such user’s Wallet or private key on our Services;</p>
        </li>
        <li><p>Violates the security of any computer network, or cracks any passwords or security encryption codes; or</p>
        </li>
        <li><p>Decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services. </p>
        </li>
      </ul>
      <p>A violation of any of the foregoing is grounds for termination of your right to use or access the Services.</p>
      <p><strong>Your Responsibilities and Assumption of Risk Associated with Virtual Currency and your Wallet</strong></p>
      <p>In order to be successfully completed, any HNS transaction created with or sent to your Wallet must be confirmed and recorded on the Handshake Network. Kyokan has no control over Handshake and therefore cannot and does not ensure that any transaction details you submit or receive via our Services will be confirmed on Handshake and does not have the ability to facilitate any cancellation or modification requests. In addition, certain interactions on Handshake and the use of TLDs may involve complex transactions that entail a high degree of risk.</p>
      <p>You agree and understand that:</p>
      <ol>
        <li><p>You: (a) have the necessary technical expertise and ability to review and evaluate the security, integrity and operation of your Wallet; (b) have the knowledge, experience, understanding, professional advice and information to make your own evaluation of the merits, risks and applicable compliance requirements under applicable laws of any use of your Wallet; (c) know, understand and accept the risks associated with your Wallet; and (d) accept the risks associated with Virtual Currency generally, and are responsible for conducting your own independent analysis of the risks specific to HNS. You further assume and agree that Kyokan will have no responsibility or liability for such risks. You hereby irrevocably waive, release and discharge all claims, whether known or unknown to you, against Kyokan, its affiliates and their respective shareholders, members, directors, officers, employees, agents and representatives related to any of the risks set forth herein.</p>
        </li>
        <li><p>You acknowledge and accept that Kyokan does not store your seed phrase, private key or other security credentials and cannot access your Wallet on your behalf in any regard. You acknowledge and accept that the loss or destruction of a hardware device you have used our Services on or installed the Wallet to may compromise the security of your Wallet and HNS and may result in the total loss of HNS.</p>
        </li>
        <li><p>You take responsibility for all activities that occur under your Wallet and accept all risks of any authorized or unauthorized access to or use of your Wallet or HNS stored in your Wallet, to the maximum extent permitted by law.</p>
        </li>
        <li><p>Virtual Currency is an emerging asset class. Kyokan makes no warranties as to the markets in which the Virtual Currency are transferred, purchased and traded.</p>
        </li>
        <li><p>The transaction details you submit via the Services may not be completed, or may be substantially delayed, by the Handshake Network used to process the transaction.</p>
        </li>
        <li><p>There are no warranties or guarantees that a transfer initiated on the Services will successfully transfer title or right in HNS or any TLDs.</p>
        </li>
        <li><p>Once transaction details have been submitted to Handshake, Kyokan cannot assist you to cancel or otherwise modify your transaction or transaction details.</p>
        </li>
        <li><p>Kyokan is not regulated by any federal or state regulatory agency and is not subject to the examination or reporting requirements of any such agencies.</p>
        </li>
        <li><p>The application of existing legal and regulatory requirements to Virtual Currency and markets for Virtual Currency is developing and evolving. Kyokan may rely on advice of counsel concerning the application of existing and new legal and regulatory requirements to its activities concerning Virtual Currency, which advice may cause us to make sudden changes to our Services.</p>
        </li>
        <li><p>Kyokan does not assume responsibility for any inherent risks associated with Blockchain technology, including, but not limited to, design or implementation flaws that affect the operation of Handshake. Furthermore, Kyokan does not assume responsibility for any issues relating to the continuing viability of Handshake, including, but not limited to, the ability to retain the technical expertise required to support Handshake or the performance of Handshake with respect to transaction times.</p>
        </li>
        <li><p>Kyokan makes no guarantee as to the functionality of Handshake’s decentralized governance processes, which could, among other things, lead to delays, conflicts of interest, or operational decisions that are unfavorable to certain owners of HNS. You acknowledge and accept that the protocol governing the operation of Handshake may be subject to sudden changes in operating rules which may materially alter Handshake and affect the value and function of HNS.</p>
        </li>
        <li><p>Kyokan does not assume responsibility for fundamental advancements in cryptography which could render inoperative the current cryptography algorithms utilized by Handshake.</p>
        </li>
        <li><p>Kyokan makes no guarantee as to the security of Handshake. Kyokan is not liable for any hacks, double spending, stolen HNS, or any other attacks on Handshake, including, but not limited to, majority attacks in which a nation-state or other party with sufficient computing power is able to control and manipulate the records of Handshake.</p>
        </li>
        <li><p>Kyokan is not liable for any hacks or malicious attempts or phishing scams to obtain access to your Wallet via your web browser or hardware devices. You alone are responsible for ensuring that you do not provide your security information to any other person and or entity.</p>
        </li>
        <li><p>Kyokan is not responsible for any illegal activity or use of the Virtual Currency contained your Wallet or for any illegal transfers requested or authorized by you, and Kyokan will not be liable or responsible for any allegations or claims related to the intellectual property rights of any other third party in connection with your use of Handshake, purchase of TLDs, or use of TLDs.</p>
        </li>
      </ol>
      <p><strong>What are my rights in the Services?</strong></p>
      <p>The materials displayed or performed or available on or through the Services, including, but not limited to, text, graphics, data, articles, photos, images, illustrations, and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, including any open source licenses, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell, commercialize or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else’s (including Kyokan’s) rights. You are the sole owner of the HNS in your Wallet and may elect to extract your private key or otherwise transfer your HNS to another Wallet or platform.</p>
      <p>You understand that, excluding any open source software or third-party software that the Services incorporate, Kyokan owns the Services, including all technology or Content (including all intellectual property rights subsisting therein), and hereby grants you a limited, revocable, transferable, license to access and use those portions of the Services that are proprietary to Kyokan. You acknowledge that the Services may use, incorporate or link to certain open-source components and that your use of the Services is subject to, and you will comply with any, applicable open-source licenses that govern any such open-source components (collectively, “Open-Source Licenses”). Without limiting the generality of the foregoing, you may not: (a) modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise use the Services in a manner that violates the licenses granted in these Terms or any other Open-Source Licenses.</p>
      <p>Any of Kyokan’s product or service names, logos, and other marks used as a part of the Services, including Kyokan&#39;s name and logo are trademarks owned by Kyokan, its affiliates or its applicable licensors. You may not copy, imitate or use them without Kyokan’s (or the applicable licensor’s) prior written consent.</p>
      <p><strong>Who is responsible for what I see and do on the Services?</strong></p>
      <p>Any third-party goods or services, information or content publicly posted or privately transmitted or made available through the Services is the sole responsibility of the person from whom such goods, services or content originated, and you obtain such goods or services and access all such information and content at your own risk, and we aren’t liable for any errors or omissions or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can’t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services.</p>
      <p>You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You are responsible for all your activity in connection with the Services.</p>
      <p>The Services may contain links or connections to third party websites or services that are not owned or controlled by Kyokan. In other cases, third party websites may integrate with our Services. When you access third party websites or use third party services, you accept that there are risks in doing so, and that Kyokan is not responsible for such risks. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each third-party website or service that you visit or utilize.</p>
      <p>Kyokan has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any third-party websites or by any third party that you interact with through the Services. In addition, Kyokan will not and cannot monitor, verify, censor or edit the content of any third-party site or service. By using the Services, you release and hold us harmless from any and all liability arising from your use of any third-party website or service.</p>
      <p>Your interactions with organizations and/or individuals found on or through the Services, including payment and delivery of goods or services, financial transactions, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that Kyokan shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.</p>
      <p>If there is a dispute between participants of the Services, or between users and any third party, you agree that Kyokan is under no obligation to become involved. In the event that you have a dispute with one or more other users or third parties, you release Kyokan, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: &quot;A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party.”</p>
      <p><strong>Will Kyokan ever change the Services?</strong></p>
      <p>We&#39;re always trying to improve the Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain</p>
      <p>features or restrict access to parts or all of the Services. We reserve the right to remove any Content from the Services at any time, for any reason in our sole discretion, and without notice.</p>
      <p><strong>Do the Services cost anything?</strong></p>
      <p>The Kyokan Services are currently free, but we reserve the right to charge for certain or all Services in the future. We will notify you before any Services you are using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services.</p>
      <p><strong>What if I want to stop using the Services?</strong></p>
      <p>You&#39;re free to do that at any time; please refer to our Privacy Policy to understand how we treat information you provide to us after you have stopped using our Services.</p>
      <p>Kyokan is also free to terminate (or suspend access to) your use of certain of the Services for any reason in our discretion, including your breach of these Terms, provided t  hat we will never have the ability to access your Wallet or transfer your HNS, even in the event we terminate your access to our other Services. Kyokan has the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms. If we suspend your use of the Services, you may continue to access your Wallet directly or through other services not hosted by us.</p>
      <p>Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us.</p>
      <p><strong>What else do I need to know?</strong></p>
      <p>Warranty Disclaimer. Neither Kyokan nor its licensors or suppliers make any representations or warranties concerning any Content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services. We (and our licensors and suppliers) make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services. Products and services purchased or offered (whether or not following such recommendations and suggestions) through the Services are provided “AS IS” and without any warranty of any kind from Kyokan or others (unless, with respect to such others only, provided expressly and unambiguously in writing by a designated third party for a specific product). THE SERVICES AND CONTENT ARE PROVIDED BY KYOKAN (AND ITS LICENSORS AND SUPPLIERS) ON AN “AS-IS” BASIS, WITHOUT WARRANTIES OR ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, OR THE SECURITY ASSOCIATED USE OF, OR TRANSMISSION OF INFORMATION THROUGH, THE SERVICES. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
      <p>Limitation of Liability.  Kyokan shall not be liable for any action taken or omitted by it pursuant to, or in connection with, these Terms except to the extent that a court of competent jurisdiction determines in a final and non-appealable judgment that Kyokan’s willful misconduct or fraud was the direct cause of any loss to you, and subject to the limitations set forth below.</p>
      <p>Notwithstanding anything to the contrary in these Terms, Kyokan shall be under no obligation to inquire into and shall not be liable for any damages, other liabilities or harm to any person or entity relating to:</p>
      <ul>
        <li><p>the ownership, validity or genuineness of HNS;</p>
        </li>
        <li><p>the collectability, insurability, effectiveness, marketability or suitability of HNS; or</p>
        </li>
        <li><p>losses, delays, failures, errors, interruptions or loss of data occurring directly or indirectly by reason of circumstances beyond Kyokan’s control, including without limitation: the failure of Handshake; acts of God; action or inaction of civil or military authority; public enemy; war; terrorism; riot; fire; flood; sabotage; epidemics or pandemics; labor disputes; civil commotion; interruption, loss or malfunction of utilities, transportation, computer or communications capabilities; insurrection; elements of nature; or non-performance by a third party.</p>
        </li>
      </ul>
      <p>Notwithstanding anything in these Terms to the contrary, TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL KYOKAN (OR ITS LICENSORS OR SUPPLIERS) BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, OR (B) ANY AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) $100 OR (II) THE AMOUNTS PAID BY YOU TO KYOKAN IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM, OR (C) ANY MATTER BEYOND OUR REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>
      <p><strong>Indemnity</strong>.  To the fullest extent allowed by applicable law, You agree to indemnify and hold Kyokan, its affiliates, officers, agents, employees, and partners harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys’ fees) arising from or in any way related to any third party allegations or claims relating to (a) your use of the Services (including any actions taken by a third party using your Wallet), and (b) your violation of these Terms. In the event of such an allegation, claim, suit, or action (“Claim”), we will attempt to provide notice of the Claim to any contact information we have for you, if applicable (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations hereunder).</p>
      <p><strong>Assignment.</strong> You may not assign, delegate or transfer these Terms or your rights or obligations hereunder, in any way (by operation of law or otherwise) without Kyokan’s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.</p>
      <p><strong>Choice of Law; Arbitration.</strong>  These Terms are governed by and will be construed under the laws of the State of California, without regard to the conflicts of laws provisions thereof. Any dispute arising from or relating to the subject matter of these Terms shall be finally settled in San Francisco County, California, in English, in accordance with the Streamlined Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, Inc. (“JAMS”) then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of JAMS arbitrators in accordance with such Rules. Judgment upon the award rendered by such arbitrator may be entered in any court of competent jurisdiction. Notwithstanding the foregoing obligation to arbitrate disputes, each party shall have the right to pursue injunctive or other equitable relief at any time, from any court of competent jurisdiction. For all purposes of this Agreement, the parties consent to exclusive jurisdiction and venue in the state or federal courts located in, respectively, San Francisco County, California, or the Northern District of California. Any arbitration under these Terms will take place on an individual basis: class arbitrations and class actions are not permitted. YOU UNDERSTAND AND AGREE THAT BY ENTERING INTO THESE TERMS, YOU AND KYOKAN ARE EACH WAIVING THE RIGHT TO TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.</p>
      <p><strong>Reporting Suspected Vulnerabilities.</strong>  If you would like to report a vulnerability or have a security concern regarding our Interface, App, or other aspects of our Services, please e-mail operations@kyokan.io.</p>
      <p><strong>Miscellaneous.</strong>  You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights hereunder. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and Kyokan agree that these Terms are the complete and exclusive statement of the mutual understanding between you and Kyokan, and that it supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of Kyokan, and you do not have any authority of any kind to bind Kyokan in any respect whatsoever.</p>
    </div>
  )
}
